from __future__ import annotations

from pathlib import Path

from rich.console import Console

from .generator import GenerationOutput
from .workspace import Workspace

console = Console()


def _write_file(base: Path, rel_path: str, content: str) -> None:
    target = base / rel_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def apply_generation(
    workspace: Workspace,
    output: GenerationOutput,
    mode: str,
) -> None:
    project_root = workspace.project_path
    if not project_root.exists():
        raise FileNotFoundError(f"Project directory missing: {project_root}")

    existing_managed = workspace.load_managed()
    existing_set = set(existing_managed)
    new_managed = [p.replace("\\", "/") for p in output.managed_paths]

    if mode == "new":
        for file in output.files:
            _write_file(project_root, file.path, file.content)
        managed_union = sorted(set(existing_set).union(new_managed))
        workspace.save_managed(managed_union)
        return

    if mode == "iterate":
        for file in output.files:
            if file.path in existing_set:
                _write_file(project_root, file.path, file.content)
        managed_union = sorted(set(existing_set).union(new_managed))
        workspace.save_managed(managed_union)
        return

    raise ValueError("mode must be 'new' or 'iterate'")


def ensure_generated_readme(workspace: Workspace) -> None:
    rel_path = "README.generated.md"
    target = workspace.project_path / rel_path
    if target.exists():
        return
    content = """# Generated App\n\nThis app was generated by `umabuild`.\n\n## Run\n\n- Install dependencies: `npm install`\n- Start Expo Web: `npx expo start --web`\n"""
    _write_file(workspace.project_path, rel_path, content)
    managed = workspace.load_managed()
    if rel_path not in managed:
        managed.append(rel_path)
        workspace.save_managed(managed)
